const ROLES = {
  STUDENT: "STUDENT",
  RECRUITER: "RECRUITER",
  ADMIN: "ADMIN",
};

const ERROR_MESSAGES = {
  UNAUTHORIZED: "Unauthorized",
  EMAIL_NOT_VERIFIED: "Email not verified",
  INVALID_ROLE: "Invalid role",
  ONBOARDING_COMPLETED: "Onboarding already completed",
  ONBOARDING_NOT_COMPLETED: "Onboarding not completed",
};
const ONBOARDING_STEPS = {
  ROLE_SELECTION: "ROLE_SELECTION",
  STUDENT_EDUCATION: "STUDENT_EDUCATION",
  STUDENT_SKILLS: "STUDENT_SKILLS",
  STUDENT_LOCATION: "STUDENT_LOCATION",
  COMPLETED: "COMPLETED",
};

const RECRUITER_ONBOARDING_STEPS = {
  ROLE_SELECTION: "ROLE_SELECTION",
  RECRUITER_PROFESSIONAL: "RECRUITER_PROFESSIONAL",
  RECRUITER_COMPANY: "RECRUITER_COMPANY",
  RECRUITER_DESCRIPTION: "RECRUITER_DESCRIPTION",
  COMPLETED: "COMPLETED",
};

const ONBOARDING_STEP_ORDER = {
  STUDENT: [
    ONBOARDING_STEPS.ROLE_SELECTION,
    ONBOARDING_STEPS.STUDENT_EDUCATION,
    ONBOARDING_STEPS.STUDENT_SKILLS,
    ONBOARDING_STEPS.STUDENT_LOCATION,
    ONBOARDING_STEPS.COMPLETED,
  ],
  RECRUITER: [
    RECRUITER_ONBOARDING_STEPS.ROLE_SELECTION,
    RECRUITER_ONBOARDING_STEPS.RECRUITER_PROFESSIONAL,
    RECRUITER_ONBOARDING_STEPS.RECRUITER_COMPANY,
    RECRUITER_ONBOARDING_STEPS.RECRUITER_DESCRIPTION,
    RECRUITER_ONBOARDING_STEPS.COMPLETED,
  ],
};


Object.freeze(ROLES);
Object.freeze(ERROR_MESSAGES);

module.exports = {
  ROLES,
  ERROR_MESSAGES,
  ONBOARDING_STEPS,
  RECRUITER_ONBOARDING_STEPS,
  ONBOARDING_STEP_ORDER,
};
